spring:
    sql.init.mode: always # Configuration qui permet d’exécuter le fichier schema.sql au démarrage de l’application
    datasource:
        url: jdbc:postgresql://localhost:5432,postgres:5432/postgres
        username: postgres
        password: example
